name: thinkio_webtool
version: 0.1.1
description: >
  Supporting tools/scripts for the development of the thinking group official website (www.thinking-grp.org).
author: Haruka Sato <as.he.that.doth.serve@gmail.com>
homepage: https://www.thinking-grp.org
repository: https://github.com/thinking-grp/thinking-grp.github.io
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  yaml: ^3.1.3
topics:
  - thinking-grp
  - website
publish_to: none
